### PR TITLE
fix daily summary endpoint

### LINKED ISSUE #303: 502: BAD_GATEWAY for the dailySummary page
The [dailySummary page](https://covid19.mathdro.id/api/daily) just brings up a 502: BAD_GATEWAY error. 

### Console produces this error message:
`Failed to load resource: the server responded with a status of 502 ()`
<br><br>
### Vercel displays this on the page:
`An error occurred with this application.
This is an error with the application itself, not the platform.`

**502**: BAD_GATEWAYCode:  `NO_RESPONSE_FROM_FUNCTION`
ID:  `sfo1::v4jkk-1601282194178-4cbf1e1b138f`

<br><br>
Screen Shot 2020-09-28 at 1 45 53 AM

### PR DESCRIPTION
**Pull request by hendrasan**
Should fix #303 but not sure if it will break when there are more daily data in the future.

### CODE REVIEW

**Comment by hendrasan** [comment]
Nevermind, worked in my machine but failed in production 😅

**Comment by hendrasan** [comment]
The problem is the endpoint timed out. It's probably because the John Hopkins API takes up to 8-10 seconds per request, more than the 10 seconds allowed by Vercel Hobby plan.

Maybe you should break the endpoint to only show X latest records or something

**Comment by npankov** [comment]
> The problem is the endpoint timed out. It's probably because the John Hopkins API takes up to 8-10 seconds per request, more than the 10 seconds allowed by Vercel Hobby plan.
> 
> Maybe you should break the endpoint to only show X latest records or something
as a result it's work?

**Comment by k1m0ch1** [comment]
@hendrasan so it is not working, I'll close this PR if not working.

**Comment by k1m0ch1** [comment]
fixed in https://github.com/mathdroid/covid-19-api/pull/315

**Pull request closed without merging**
