### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iamazik**
Add a new supported application based on this API.

### CODE REVIEW

**Comment by ashishkumar-xx** [comment]
can i use for my website for free?

**Comment by iamazik** [comment]
It's completely open source and as well as free. However, it's a desktop app. This means you can't use on your website.

**Comment by ashishkumar-xx** [comment]
Can you suggest something for my website ?

**Comment by iamazik** [comment]
I’m afraid to say that I’m not sure how you can implement it on your website as it depends on how your website was made and how you would like to implement it 😐

**Comment by mathdroid** [comment]
LGTM, thank you for your project!

**Pull request merged**
